Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -44,13 +44,13 @@ jobs:
             git fetch origin master && git reset --hard origin/master || { echo "Fetch or reset failed, skipping..."; true; }
   
             git add --all
-            git commit -am "Auto-update server changes" --allow-empty -q || echo "Git commit failed"
+            git commit -am "Auto-update server changes" -q || echo "Git commit failed"
   
             for i in {1..3}; do
             git push -f && break || { echo "Push failed, retrying... ($i)"; sleep 5; }
             done || echo "Push failed after multiple attempts"
 
-            sleep 180
+            sleep 90
           done' &
 
           # Start the Minecraft server with optimized flags for performance
